Fixing bug introduced by PyTorch 1.10
facebookresearch/PyTorch-BigGraph pull request #246
Opened 2022-01-19 19:04 UTC by tmarkovich

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context / Related issue

This fixes issue #245.

## How Has This Been Tested (if it applies)

I've confirmed that I've been able to train on PyTorch 1.10 using this fix.

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

2022-01-19 19:19 UTC, adamlerer requested changes
Thanks! Would it be possible to make this small change? I want to confirm that the error is really because of the `expand` rather than because of `new_zeros`.

2022-01-19 19:19 UTC, adamlerer commented on torchbiggraph/losses.py
> +                torch.zeros((num_pos, ), dtype=torch.long, device=scores.device),
```suggestion
                pos_scores.new_zeros((num_pos, ), dtype=torch.long),
```

2022-01-19 19:19 UTC, adamlerer commented on torchbiggraph/losses.py
> +                torch.zeros((num_pos, ), dtype=torch.long, device=scores.device),
```suggestion
                pos_scores.new_zeros((num_pos, ), dtype=torch.long),
```

2022-01-20 12:53 UTC, lw commented
This change is undoing a perf optimization: the code before was carefully written to allocate only one element in memory, and then adapt the tensor's indexing so that it _looks like_ that element is replicated many times. The new code however allocates multiple elements in memory. I don't know if the impact is significant, but it would certainly be better to avoid it.

If there has been a regression in PyTorch between 1.9 and 1.10 that should be reported upstream and ideally fixed there, instead of working around it in our code.

2022-01-20 14:39 UTC, tmarkovich commented
@lw I agree in principal, but the timeframe on which the upstream bug will be fixed. I've also observed almost no performance degradation in practice with the above change -- with 16 A100 GPUs I'm able to train at 46m edges/second with pytorch 1.9 and `new_zeros` or pytorch 1.10 and the above change.

@adamlerer I did find that the issue is down to the `expand` and not the difference between `zeros` and `new_zeros`.

@lw with that the above in mind, what is the perf difference between `new_zeros((), ...).expand(npos)` and `new_zeros((npos, ))`?

<img width="1088" alt="Screen Shot 2022-01-20 at 9 34 47 AM" src="https://user-images.githubusercontent.com/339699/150359582-e4b86315-8d8f-44f7-80c1-26514206fa03.png">

Anyway, I'll report this bug upstream to pytorch as well.

2022-01-20 14:44 UTC, lw commented
> what is the perf difference between new_zeros((), ...).expand(npos) and new_zeros((npos, ))?

It's more of a memory gain (and, secondarily, the time gain to allocate/fill in that memory). But admittedly it's probably barely significant, since if I remember correctly we're talking about allocating 4 extra bytes for each input edge of a batch (rather than just 4 bytes once for the entire batch).

If you've confirmed that the `expand` is indeed the root cause of the bug and that there's no observable difference after this fix, then I'm fine with it. Thanks for reporting the bug upstream anyways!

2022-01-20 14:50 UTC, tmarkovich commented
I'll go ahead and change to `new_zeros((npos, ))` and then add an issue to revert the fix once the upstream bug is fixed (with linked issue).

In the mean time, here's the upstream issue:
https://github.com/pytorch/pytorch/issues/71550

2022-01-20 14:59 UTC, adamlerer commented
@lw you're right that there's a (minor) performance implication to this, but I think it's overshadowed by the benefit of PyTorch 1.10 compatibility (even if this is fixed in a future version, we ideally want compatibility across a range of pytorch versions).

2022-01-20 21:51 UTC, ngimel commented
It is indeed fixed in point release (which everyone should be using instead of 1.10) https://github.com/pytorch/pytorch/pull/69617/files#diff-13bb6989036251a34e2a9f7bd28349761c20950940cd22300a72ffc860296ed0R285, but it's fixed in a way to undo your perf optimization inside cross-entropy implementation, by calling `contiguous()` on your expanded tensor.

2022-01-27 14:54 UTC, tmarkovich commented
I just wanted to check in -- it looks like this was imported into the Meta internal repo  -- did it get mainlined externally? If so, should we close this PR? And if not, should I make any changes?

2022-02-06 17:27 UTC, adamlerer commented
> It is indeed fixed in point release (which everyone should be using instead of 1.10) https://github.com/pytorch/pytorch/pull/69617/files#diff-13bb6989036251a34e2a9f7bd28349761c20950940cd22300a72ffc860296ed0R285, but it's fixed in a way to undo your perf optimization inside cross-entropy implementation, by calling `contiguous()` on your expanded tensor.

What is "point release" @ngimel ?

2022-02-06 17:43 UTC, adamlerer commented
Sorry about the delay @tmarkovich , this PR should merge today.

2022-02-07 16:58 UTC, closed without merging

2022-02-07 20:13 UTC, ngimel commented
> What is "point release" @ngimel ?

1.10.1 or 1.10.2 (it's fixed in both).